server:
  port: 8665
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/site_dev?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    pool:
      enabled: true
      max-size: 50
      initial-size: 10
      validation-query: select 1
  application:
    name: lanrenspace.site
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: true


logging:
  level:
    com.lanrenspace.kakami: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.apache.ibatis.r2dbc: DEBUG